name: Build and Test 🔧

on:
  push:
    branches:
      - main
  pull_request:

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ⬇️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install NPM Deps 🌎
        run: npm install

      - name: Lint 🌟
        run: npm run lint

      - name: Build 🔧
        run: npm run build:ci

      - name: Tests 🧪
        run: npm run test:ci

      - name: Coveralls 📊
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
